export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'


export const USER_LOGIN = 'USER_LOGIN'

export const TUTOR_ACTIONS = {
    FETCH_TUTORS : 'FETCH_TUTORS',
    RECEIVE_TUTORS:'RECEIVE_TUTORS'

}
export const SAGA_ACTIONS = {
    FETCHING_DATA_SUCCESS : 'FETCHING_DATA_SUCCESS',
    FETCHING_DATA_FAILURE:'FETCHING_DATA_FAILURE',
    FETCHING_DATA:'FETCHING_DATA'

}